import type {
  Collection,
  DemoStore,
  Profile,
  Restaurant,
  RestaurantVisit,
  UserPreferences,
  UserRestaurant,
} from "../types";
import { DEFAULT_WEIGHTS } from "../types";

const DEMO_USER_ID = "demo_user";

function r(
  partial: Omit<Restaurant, "createdAt" | "updatedAt" | "isDemo" | "provider" | "country"> &
    Partial<Pick<Restaurant, "provider" | "country">>,
): Restaurant {
  const now = "2026-01-15T00:00:00.000Z";
  return {
    country: "Indonesia",
    provider: "demo",
    isDemo: true,
    createdAt: now,
    updatedAt: now,
    ...partial,
  };
}

/** Demo restaurants — names/addresses aligned with Google Maps listings. */
export const DEMO_RESTAURANTS: Restaurant[] = [
  r({
    id: "rest_sushi_masa",
    name: "Sushi Masa",
    slug: "sushi-masa",
    address: "Jl. Tuna Raya No.5 Lantai 3, Muara Baru, Penjaringan",
    area: "Muara Baru",
    city: "Jakarta",
    latitude: -6.1065,
    longitude: 106.7968,
    cuisine: "Japanese",
    category: "Restaurant",
    priceLevel: 4,
    externalRating: 4.6,
    externalReviewCount: 4200,
    openingHours: "11:30–14:00, 18:00–22:00",
    photoUrl:
      "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&q=80",
    providerPlaceId: "demo_sushi_masa",
  }),
  r({
    id: "rest_osteria_gia",
    name: "Osteria Gia",
    slug: "osteria-gia",
    address: "Pacific Place Mall Ground Level, SCBD Lot 3-5, Jl. Jenderal Sudirman",
    area: "SCBD",
    city: "Jakarta",
    latitude: -6.2255,
    longitude: 106.8094,
    cuisine: "Italian",
    category: "Restaurant",
    priceLevel: 3,
    externalRating: 4.6,
    externalReviewCount: 980,
    openingHours: "11:00–22:00",
    photoUrl:
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    providerPlaceId: "demo_osteria_gia",
  }),
  r({
    id: "rest_pagi_sore",
    name: "Rumah Makan Pagi Sore",
    slug: "rumah-makan-pagi-sore",
    address: "Jl. KS Tubun No.2H, Slipi, Palmerah",
    area: "Slipi",
    city: "Jakarta",
    latitude: -6.2015,
    longitude: 106.7978,
    cuisine: "Indonesian",
    category: "Restaurant",
    priceLevel: 2,
    externalRating: 4.4,
    externalReviewCount: 3200,
    openingHours: "10:00–21:00",
    photoUrl:
      "https://images.unsplash.com/photo-1555939596-57671181d2e8?w=800&q=80",
    providerPlaceId: "demo_pagi_sore",
  }),
  r({
    id: "rest_pierre",
    name: "Pierre - Grand Hyatt Jakarta",
    slug: "pierre-grand-hyatt-jakarta",
    address: "Grand Hyatt Jakarta, Jl. MH Thamrin Kav. 28-30",
    area: "Thamrin",
    city: "Jakarta",
    latitude: -6.1948,
    longitude: 106.8215,
    cuisine: "French",
    category: "Fine Dining",
    priceLevel: 4,
    externalRating: 4.8,
    externalReviewCount: 450,
    openingHours: "18:00–23:00",
    photoUrl:
      "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80",
    providerPlaceId: "demo_pierre",
  }),
  r({
    id: "rest_sate_senayan",
    name: "Sate Khas Senayan",
    slug: "sate-khas-senayan",
    address: "Plaza Senayan Level 1, Jl. Asia Afrika No.8",
    area: "Senayan",
    city: "Jakarta",
    latitude: -6.225,
    longitude: 106.799,
    cuisine: "Indonesian",
    category: "Restaurant",
    priceLevel: 2,
    externalRating: 4.3,
    externalReviewCount: 5100,
    openingHours: "10:00–22:00",
    photoUrl:
      "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800&q=80",
    providerPlaceId: "demo_sate_senayan",
  }),
  r({
    id: "rest_uma_oma",
    name: "Uma Oma Cafe",
    slug: "uma-oma-cafe",
    address: "Jl. Melawai I No.28, Melawai, Kebayoran Baru",
    area: "Blok M",
    city: "Jakarta",
    latitude: -6.2446,
    longitude: 106.8008,
    cuisine: "Indonesian",
    category: "Cafe",
    priceLevel: 2,
    externalRating: 4.5,
    externalReviewCount: 620,
    openingHours: "09:00–22:00",
    photoUrl:
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
    providerPlaceId: "demo_uma_oma",
  }),
  r({
    id: "rest_common_ground",
    name: "Common Grounds",
    slug: "common-grounds-ashta",
    address: "ASHTA District 8, SCBD Lot 28, Jl. Jenderal Sudirman",
    area: "SCBD",
    city: "Jakarta",
    latitude: -6.2278,
    longitude: 106.809,
    cuisine: "Coffee",
    category: "Cafe",
    priceLevel: 2,
    externalRating: 4.4,
    externalReviewCount: 1800,
    openingHours: "07:00–22:00",
    photoUrl:
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    providerPlaceId: "demo_common_grounds",
  }),
  r({
    id: "rest_din_tai_fung",
    name: "Din Tai Fung",
    slug: "din-tai-fung-pacific-place",
    address: "Pacific Place Mall Level 2, SCBD, Jl. Jenderal Sudirman",
    area: "SCBD",
    city: "Jakarta",
    latitude: -6.2258,
    longitude: 106.8095,
    cuisine: "Chinese",
    category: "Restaurant",
    priceLevel: 3,
    externalRating: 4.5,
    externalReviewCount: 4200,
    openingHours: "10:00–22:00",
    photoUrl:
      "https://images.unsplash.com/photo-1525755662778-989d0524087e?w=800&q=80",
    providerPlaceId: "demo_din_tai_fung",
  }),
  r({
    id: "rest_seoul_garden",
    name: "Seoul Garden",
    slug: "seoul-garden-plaza-indonesia",
    address: "Plaza Indonesia Level 4, Jl. MH Thamrin Kav. 28-30",
    area: "Thamrin",
    city: "Jakarta",
    latitude: -6.1935,
    longitude: 106.822,
    cuisine: "Korean",
    category: "Restaurant",
    priceLevel: 3,
    externalRating: 4.2,
    externalReviewCount: 1100,
    openingHours: "11:00–22:00",
    photoUrl:
      "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=800&q=80",
    providerPlaceId: "demo_seoul_garden",
  }),
  r({
    id: "rest_holywings",
    name: "Holywings Melawai",
    slug: "holywings-melawai",
    address: "Jl. Melawai Raya No.189, Melawai, Kebayoran Baru",
    area: "Blok M",
    city: "Jakarta",
    latitude: -6.2435,
    longitude: 106.8005,
    cuisine: "Western",
    category: "Bar & Grill",
    priceLevel: 2,
    externalRating: 4.1,
    externalReviewCount: 2900,
    openingHours: "12:00–02:00",
    photoUrl:
      "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80",
    providerPlaceId: "demo_holywings",
  }),
  r({
    id: "rest_kintaro",
    name: "Kintaro Sushi",
    slug: "kintaro-sushi-blok-m",
    address: "Jl. Melawai Raya No.27-29, Melawai, Kebayoran Baru",
    area: "Blok M",
    city: "Jakarta",
    latitude: -6.2448,
    longitude: 106.7988,
    cuisine: "Japanese",
    category: "Restaurant",
    priceLevel: 2,
    externalRating: 4.3,
    externalReviewCount: 1500,
    openingHours: "11:00–21:30",
    photoUrl:
      "https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=800&q=80",
    providerPlaceId: "demo_kintaro",
  }),
  r({
    id: "rest_menteng_park",
    name: "Plataran Menteng",
    slug: "plataran-menteng",
    address: "Jl. HOS Cokroaminoto No.42, Gondangdia, Menteng",
    area: "Menteng",
    city: "Jakarta",
    latitude: -6.1955,
    longitude: 106.8305,
    cuisine: "Indonesian",
    category: "Fine Dining",
    priceLevel: 4,
    externalRating: 4.6,
    externalReviewCount: 780,
    openingHours: "11:00–22:00",
    photoUrl:
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    providerPlaceId: "demo_plataran",
  }),
  r({
    id: "rest_tokyo_belly",
    name: "Tokyo Belly",
    slug: "tokyo-belly-plaza-indonesia",
    address: "Plaza Indonesia Level 4, Jl. MH Thamrin Kav. 28-30",
    area: "Thamrin",
    city: "Jakarta",
    latitude: -6.1938,
    longitude: 106.8225,
    cuisine: "Japanese",
    category: "Casual",
    priceLevel: 2,
    externalRating: 4.2,
    externalReviewCount: 960,
    openingHours: "10:00–22:00",
    photoUrl:
      "https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&q=80",
    providerPlaceId: "demo_tokyo_belly",
  }),
  r({
    id: "rest_nara",
    name: "Nara",
    slug: "nara-senopati",
    address: "Jl. Senopati No.86, Senopati, Kebayoran Baru",
    area: "Senopati",
    city: "Jakarta",
    latitude: -6.2324,
    longitude: 106.8112,
    cuisine: "Japanese",
    category: "Restaurant",
    priceLevel: 3,
    externalRating: 4.5,
    externalReviewCount: 540,
    openingHours: "10:00–23:00",
    photoUrl:
      "https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&q=80",
    providerPlaceId: "demo_nara",
  }),
  r({
    id: "rest_lucca",
    name: "Lucca",
    slug: "lucca-kemang",
    address: "Jl. Kemang Raya No.10, Bangka, Mampang Prapatan",
    area: "Kemang",
    city: "Jakarta",
    latitude: -6.2595,
    longitude: 106.8122,
    cuisine: "Italian",
    category: "Restaurant",
    priceLevel: 3,
    externalRating: 4.4,
    externalReviewCount: 410,
    openingHours: "11:00–23:00",
    photoUrl:
      "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&q=80",
    providerPlaceId: "demo_lucca",
  }),
  r({
    id: "rest_seafood_pik",
    name: "Bandar Djakarta",
    slug: "bandar-djakarta-pik",
    address: "PIK Avenue, Jl. Pantai Indah Kapuk Boulevard",
    area: "PIK",
    city: "Jakarta",
    latitude: -6.1095,
    longitude: 106.741,
    cuisine: "Seafood",
    category: "Restaurant",
    priceLevel: 3,
    externalRating: 4.3,
    externalReviewCount: 2200,
    openingHours: "11:00–22:00",
    photoUrl:
      "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80",
    providerPlaceId: "demo_bandar",
  }),
  r({
    id: "rest_gading_coffee",
    name: "Anomali Coffee",
    slug: "anomali-coffee-pik",
    address: "PIK Avenue Ground Floor, Pantai Indah Kapuk",
    area: "PIK",
    city: "Jakarta",
    latitude: -6.1102,
    longitude: 106.7395,
    cuisine: "Coffee",
    category: "Cafe",
    priceLevel: 2,
    externalRating: 4.4,
    externalReviewCount: 890,
    openingHours: "08:00–21:00",
    photoUrl:
      "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80",
    providerPlaceId: "demo_anomali",
  }),
  r({
    id: "rest_warung_tekko",
    name: "Warung Tekko",
    slug: "warung-tekko-kebayoran-park",
    address: "Kebayoran Park Mall Ground Floor, Jl. Ciledug Raya No.18, Kebayoran Lama",
    area: "Kebayoran Lama",
    city: "Jakarta",
    latitude: -6.2388,
    longitude: 106.7825,
    cuisine: "Indonesian",
    category: "Restaurant",
    priceLevel: 1,
    externalRating: 4.5,
    externalReviewCount: 3400,
    openingHours: "10:00–22:00",
    photoUrl:
      "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&q=80",
    providerPlaceId: "demo_tekko",
  }),
  r({
    id: "rest_burger_bros",
    name: "Burgreens",
    slug: "burgreens-gunawarman",
    address: "Jl. Gunawarman No.67, Senopati, Kebayoran Baru",
    area: "Senopati",
    city: "Jakarta",
    latitude: -6.2328,
    longitude: 106.8125,
    cuisine: "Healthy",
    category: "Casual",
    priceLevel: 2,
    externalRating: 4.3,
    externalReviewCount: 700,
    openingHours: "09:00–21:00",
    photoUrl:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
    providerPlaceId: "demo_burgreens",
  }),
  r({
    id: "rest_pho_saigon",
    name: "Pho 24",
    slug: "pho-24-grand-indonesia",
    address: "Grand Indonesia West Mall Level 3, Jl. MH Thamrin No.1",
    area: "Thamrin",
    city: "Jakarta",
    latitude: -6.1952,
    longitude: 106.821,
    cuisine: "Vietnamese",
    category: "Casual",
    priceLevel: 2,
    externalRating: 4.1,
    externalReviewCount: 1300,
    openingHours: "10:00–22:00",
    photoUrl:
      "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800&q=80",
    providerPlaceId: "demo_pho24",
  }),
  r({
    id: "rest_canggu_surf",
    name: "The Lawn Canggu",
    slug: "the-lawn-canggu",
    address: "Jl. Pantai Berawa No.8X, Canggu, Badung",
    area: "Canggu",
    city: "Bali",
    latitude: -8.6595,
    longitude: 115.1328,
    cuisine: "Western",
    category: "Beach Club",
    priceLevel: 3,
    externalRating: 4.4,
    externalReviewCount: 1600,
    openingHours: "08:00–23:00",
    photoUrl:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80",
    providerPlaceId: "demo_lawn",
  }),
  r({
    id: "rest_warung_made",
    name: "Warung Made",
    slug: "warung-made-seminyak",
    address: "Jl. Raya Seminyak No.21A, Seminyak, Badung",
    area: "Seminyak",
    city: "Bali",
    latitude: -8.6905,
    longitude: 115.1682,
    cuisine: "Indonesian",
    category: "Restaurant",
    priceLevel: 2,
    externalRating: 4.2,
    externalReviewCount: 2400,
    openingHours: "08:00–23:00",
    photoUrl:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&q=80",
    providerPlaceId: "demo_warung_made",
  }),
];

function ur(
  restaurantId: string,
  status: UserRestaurant["status"],
  extra: Partial<UserRestaurant> = {},
): UserRestaurant {
  const now = "2026-02-01T00:00:00.000Z";
  return {
    id: `ur_${restaurantId}`,
    userId: DEMO_USER_ID,
    restaurantId,
    status,
    personalRating: null,
    priority: "medium",
    notes: "",
    favorite: status === "favorite",
    recommendedMenu: "",
    tags: [],
    source: "demo",
    wouldVisitAgain: null,
    dateAdded: now,
    lastVisited: null,
    createdAt: now,
    updatedAt: now,
    ...extra,
  };
}

export const DEMO_USER_RESTAURANTS: UserRestaurant[] = [
  ur("rest_sushi_masa", "wishlist", {
    priority: "high",
    tags: ["Japanese", "Date Night", "Fine Dining"],
    recommendedMenu: "Omakase, Uni don",
    notes: "Must try when in Muara Baru",
  }),
  ur("rest_osteria_gia", "favorite", {
    personalRating: 4.8,
    favorite: true,
    tags: ["Italian", "Date Night"],
    recommendedMenu: "Truffle pasta",
    lastVisited: "2026-08-05T00:00:00.000Z",
    wouldVisitAgain: true,
  }),
  ur("rest_pagi_sore", "visited", {
    personalRating: 4.2,
    tags: ["Indonesian", "Comfort Food"],
    recommendedMenu: "Rendang, Gulai otak",
    lastVisited: "2026-07-12T00:00:00.000Z",
    wouldVisitAgain: true,
  }),
  ur("rest_pierre", "favorite", {
    personalRating: 5,
    favorite: true,
    priority: "high",
    tags: ["Fine Dining", "Date Night"],
    recommendedMenu: "Tasting menu",
    lastVisited: "2026-03-20T00:00:00.000Z",
  }),
  ur("rest_sate_senayan", "visited", {
    personalRating: 4.0,
    tags: ["Indonesian", "Casual"],
    recommendedMenu: "Sate ayam, Gado-gado",
    lastVisited: "2026-06-01T00:00:00.000Z",
  }),
  ur("rest_uma_oma", "wishlist", {
    priority: "high",
    tags: ["Indonesian", "Date Night"],
    notes: "Heard great things about the rijsttafel",
  }),
  ur("rest_common_ground", "favorite", {
    personalRating: 4.5,
    favorite: true,
    tags: ["Coffee", "Brunch"],
    recommendedMenu: "Flat white, avocado toast",
    lastVisited: "2026-09-01T00:00:00.000Z",
  }),
  ur("rest_din_tai_fung", "visited", {
    personalRating: 4.3,
    tags: ["Chinese", "Casual"],
    recommendedMenu: "Xiao long bao",
    lastVisited: "2026-05-18T00:00:00.000Z",
  }),
  ur("rest_seoul_garden", "wishlist", {
    priority: "medium",
    tags: ["Korean", "Group Dinner"],
  }),
  ur("rest_kintaro", "visited", {
    personalRating: 4.1,
    tags: ["Japanese", "Casual"],
    recommendedMenu: "Salmon sashimi set",
    lastVisited: "2026-04-22T00:00:00.000Z",
  }),
  ur("rest_menteng_park", "wishlist", {
    priority: "medium",
    tags: ["Indonesian", "Fine Dining"],
  }),
  ur("rest_nara", "wishlist", {
    priority: "low",
    tags: ["Japanese"],
  }),
  ur("rest_lucca", "visited", {
    personalRating: 4.4,
    tags: ["Italian"],
    lastVisited: "2026-02-14T00:00:00.000Z",
  }),
  ur("rest_warung_tekko", "favorite", {
    personalRating: 4.6,
    favorite: true,
    tags: ["Indonesian", "Street Food", "Late Night"],
    recommendedMenu: "Nasi campur",
    lastVisited: "2026-08-28T00:00:00.000Z",
  }),
  ur("rest_burger_bros", "wishlist", {
    priority: "medium",
    tags: ["Healthy"],
  }),
  ur("rest_canggu_surf", "wishlist", {
    priority: "high",
    tags: ["Western", "Bali Trip"],
    notes: "For next Bali trip",
  }),
  ur("rest_warung_made", "visited", {
    personalRating: 4.0,
    tags: ["Indonesian", "Bali Trip"],
    lastVisited: "2025-12-10T00:00:00.000Z",
  }),
];

export const DEMO_VISITS: RestaurantVisit[] = [
  {
    id: "visit_1",
    userId: DEMO_USER_ID,
    restaurantId: "rest_osteria_gia",
    visitDate: "2026-08-05",
    rating: 4.8,
    foodRating: 5,
    serviceRating: 4.5,
    ambienceRating: 4.8,
    valueRating: 4.2,
    spending: 850000,
    orderedItems: "Truffle pasta, tiramisu",
    notes: "Perfect date night",
    wouldReturn: true,
    companion: "Partner",
    createdAt: "2026-08-05T20:00:00.000Z",
  },
  {
    id: "visit_2",
    userId: DEMO_USER_ID,
    restaurantId: "rest_osteria_gia",
    visitDate: "2026-03-12",
    rating: 4.5,
    foodRating: 4.5,
    serviceRating: 4.5,
    ambienceRating: 4.5,
    valueRating: 4,
    spending: 720000,
    orderedItems: "Carbonara, wine",
    notes: "Still excellent",
    wouldReturn: true,
    companion: "Friends",
    createdAt: "2026-03-12T21:00:00.000Z",
  },
  {
    id: "visit_3",
    userId: DEMO_USER_ID,
    restaurantId: "rest_pagi_sore",
    visitDate: "2026-07-12",
    rating: 4.2,
    foodRating: 4.5,
    serviceRating: 4,
    ambienceRating: 3.8,
    valueRating: 4.5,
    spending: 280000,
    orderedItems: "Rendang, gulai, nasi",
    notes: "Comfort food hit",
    wouldReturn: true,
    companion: "Family",
    createdAt: "2026-07-12T13:00:00.000Z",
  },
  {
    id: "visit_4",
    userId: DEMO_USER_ID,
    restaurantId: "rest_common_ground",
    visitDate: "2026-09-01",
    rating: 4.5,
    foodRating: 4.3,
    serviceRating: 4.5,
    ambienceRating: 4.6,
    valueRating: 4,
    spending: 120000,
    orderedItems: "Flat white, avocado toast",
    notes: "WFH spot",
    wouldReturn: true,
    companion: "Solo",
    createdAt: "2026-09-01T10:00:00.000Z",
  },
  {
    id: "visit_5",
    userId: DEMO_USER_ID,
    restaurantId: "rest_warung_tekko",
    visitDate: "2026-08-28",
    rating: 4.6,
    foodRating: 4.8,
    serviceRating: 4,
    ambienceRating: 3.5,
    valueRating: 5,
    spending: 65000,
    orderedItems: "Nasi campur",
    notes: "Late night craving solved",
    wouldReturn: true,
    companion: "Friends",
    createdAt: "2026-08-28T23:00:00.000Z",
  },
  {
    id: "visit_6",
    userId: DEMO_USER_ID,
    restaurantId: "rest_sushi_masa",
    visitDate: "2026-01-20",
    rating: 4.7,
    foodRating: 5,
    serviceRating: 4.5,
    ambienceRating: 4.5,
    valueRating: 4,
    spending: 1200000,
    orderedItems: "Omakase",
    notes: "Wishlist fulfilled once — want again",
    wouldReturn: true,
    companion: "Partner",
    createdAt: "2026-01-20T19:00:00.000Z",
  },
];

export const DEMO_COLLECTIONS: Collection[] = [
  {
    id: "col_date_night",
    userId: DEMO_USER_ID,
    name: "Date Night",
    description: "Special spots for dinner dates",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    restaurantIds: ["rest_sushi_masa", "rest_osteria_gia", "rest_pierre", "rest_uma_oma"],
  },
  {
    id: "col_jakarta_wishlist",
    userId: DEMO_USER_ID,
    name: "Jakarta Wishlist",
    description: "Places to try in Jakarta",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    restaurantIds: [
      "rest_sushi_masa",
      "rest_uma_oma",
      "rest_seoul_garden",
      "rest_menteng_park",
      "rest_nara",
      "rest_burger_bros",
    ],
  },
  {
    id: "col_bali_trip",
    userId: DEMO_USER_ID,
    name: "Bali Food Trip",
    description: "Canggu & Seminyak picks",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    restaurantIds: ["rest_canggu_surf", "rest_warung_made"],
  },
  {
    id: "col_coffee",
    userId: DEMO_USER_ID,
    name: "Coffee Shops",
    description: "Caffeine stops",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    restaurantIds: ["rest_common_ground", "rest_gading_coffee"],
  },
];

export const DEMO_PROFILE: Profile = {
  id: DEMO_USER_ID,
  email: "demo@kaniacraves.app",
  displayName: "Kania",
  avatarUrl: null,
  createdAt: "2026-01-01T00:00:00.000Z",
};

export const DEMO_PREFERENCES: UserPreferences = {
  userId: DEMO_USER_ID,
  cuisineWeights: {
    Japanese: 32,
    Indonesian: 21,
    Italian: 15,
    Chinese: 12,
    Coffee: 10,
    Korean: 5,
    Western: 5,
  },
  pricePreference: 3,
  saveLocationHistory: false,
  recommendationWeights: DEFAULT_WEIGHTS,
  favoriteAreas: ["Senopati", "SCBD", "Blok M"],
  budgetPreference: "100–250k",
};

export function createDemoStore(): DemoStore {
  return {
    profile: structuredClone(DEMO_PROFILE),
    restaurants: structuredClone(DEMO_RESTAURANTS),
    userRestaurants: structuredClone(DEMO_USER_RESTAURANTS),
    visits: structuredClone(DEMO_VISITS),
    collections: structuredClone(DEMO_COLLECTIONS),
    preferences: structuredClone(DEMO_PREFERENCES),
    recommendationFeedback: [],
  };
}

export { DEMO_USER_ID };
